config/routes.rb
Rails.application.routes.draw do

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :data, only: [ :index, :create ] do
		get :twod, on: :collection
		get :tag_new_with, on: :collection
		get :live, on: :collection
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_point.rb
# X - Roll - φ
# Y - Pitch - θ
# Z - Yaw - ψ

# accelleration:
# acc_x = 1g * sinθ * cosφ
# acc_y = - 1g * sinθ * sinφ
# acc_z = 1g * cosθ
# → acc_y/acc_x = - tanφ

class DataPoint < ActiveRecord::Base

	acts_as_taggable_array_on :tags

	def self.tag_new_with( tags = [] )
		self.all.where( tags: '{}' ).where( 'created_at < ?', Time.now ).find_each do |data_point|
			data_point.update( tags: tags )
		end
	end

	def delta_antigravity
		{ xaxis: -angle_xaxis+90, yaxis: -angle_yaxis, zaxis: angle_zaxis }
	end

	def delta_gravity
		{ xaxis: -angle_xaxis-90, yaxis: -angle_yaxis, zaxis: angle_zaxis }
	end

	# angle 1g acceleration
	def angle_acceleration_xaxis
		Math.sin(to_radians(angle_yaxis)) * Math.cos(to_radians(angle_xaxis)) # acc_x = 1g * sinθ * cosφ
	end

	def angle_acceleration_yaxis
		- Math.sin(to_radians(angle_yaxis)) * Math.sin(to_radians(angle_xaxis)) # acc_y = - 1g * sinθ * sinφ
	end

	def angle_acceleration_zaxis
		Math.cos(to_radians(angle_yaxis)) # acc_z = 1g * cosθ
	end

	def angle_acceleration_vector_length
		Math.sqrt( angle_acceleration_xaxis**2 + angle_acceleration_yaxis**2 + angle_acceleration_zaxis**2 )
	end


	# gravity vector calculations
	def gravity_acceleration_xaxis
		Math.sin(to_radians(delta_gravity[:yaxis])) * Math.cos(to_radians(delta_gravity[:xaxis]))
	end

	def gravity_acceleration_yaxis
		- Math.sin(to_radians(delta_gravity[:yaxis])) * Math.sin(to_radians(delta_gravity[:xaxis]))
	end

	def gravity_acceleration_zaxis
		Math.cos(to_radians(delta_gravity[:yaxis]))
	end

	def gravity_acceleration_vector_length
		Math.sqrt( gravity_acceleration_xaxis**2 + gravity_acceleration_yaxis**2 + gravity_acceleration_zaxis**2 )
	end


	# corrected vector calculations
	def corrected_acceleration_xaxis
		acceleration_xaxis - gravity_acceleration_xaxis
	end

	def corrected_acceleration_yaxis
		acceleration_yaxis - gravity_acceleration_yaxis
	end

	def corrected_acceleration_zaxis
		acceleration_zaxis - gravity_acceleration_zaxis
	end

	def corrected_acceleration_vector_length
		Math.sqrt( corrected_acceleration_xaxis**2 + corrected_acceleration_yaxis**2 + corrected_acceleration_zaxis**2 )
	end



	# acceleration vector
	def acceleration_vector_angle_xaxis #pitch
		to_degrees( Math.atan2( acceleration_yaxis, acceleration_zaxis ) )
	end

	def acceleration_vector_angle_yaxis #yaw
		angle = to_degrees( Math.atan2( acceleration_zaxis, acceleration_xaxis ) )
		if acceleration_zaxis > 0
			angle = angle - 90
			angle = 360 + angle if angle < -180
		else
			angle = angle + 90
			angle = -360 + angle if angle > 180
		end

		angle
	end

	def acceleration_vector_angle_zaxis #roll
		# atan (accelerationY/sqrt(accelerationX*accelerationX + accelerationZ*accelerationZ)
		# to_degrees( Math.atan2( acceleration_yaxis, Math.sqrt( acceleration_xaxis**2 + acceleration_zaxis**2 ) ) )
		# to_degrees( Math.atan( -acceleration_xaxis / Math.sqrt( acceleration_yaxis**2 + acceleration_zaxis**2 ) ) )
		to_degrees( Math.atan2( acceleration_yaxis, acceleration_zaxis ) )
	end

	def acceleration_vector_length
		Math.sqrt( acceleration_xaxis**2 + acceleration_yaxis**2 + acceleration_zaxis**2 )
	end






	# helper fucntions
	def to_radians( degrees )
		degrees/180 * Math::PI
	end

	def to_degrees( radians )
		radians * (180/Math::PI)
	end

	def to_s
		JSON.pretty_generate( self.attributes.merge(
			acceleration_vector_length: self.acceleration_vector_length,

			# acceleration_vector_angle_xaxis: self.acceleration_vector_angle_xaxis,
			# acceleration_vector_angle_yaxis: self.acceleration_vector_angle_yaxis,
			# acceleration_vector_angle_zaxis: self.acceleration_vector_angle_zaxis,

			gravity_acceleration: '-----------------',
			gravity_acceleration_xaxis: self.gravity_acceleration_xaxis,
			gravity_acceleration_yaxis: self.gravity_acceleration_yaxis,
			gravity_acceleration_zaxis: self.gravity_acceleration_zaxis,
			gravity_acceleration_vector_length: self.gravity_acceleration_vector_length,

			corrected_acceleration: '-----------------',
			corrected_acceleration_xaxis: self.corrected_acceleration_xaxis,
			corrected_acceleration_yaxis: self.corrected_acceleration_yaxis,
			corrected_acceleration_zaxis: self.corrected_acceleration_zaxis,
			corrected_acceleration_vector_length: self.corrected_acceleration_vector_length,

			angle_acceleration: '-----------------',
			angle_acceleration_xaxis: self.angle_acceleration_xaxis,
			angle_acceleration_yaxis: self.angle_acceleration_yaxis,
			angle_acceleration_zaxis: self.angle_acceleration_zaxis,
			angle_acceleration_vector_length: self.angle_acceleration_vector_length,
		) )
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/data_controller.rb
class DataController < ActionController::Base

	def create
		render plain: 'Create OK', layout: false, status: 200

		property_names = [ 'device_name', 'device_id', 'logged_at', 'time_delta', 'date', 'time', 'acceleration_xaxis', 'acceleration_yaxis', 'acceleration_zaxis', 'angular_velocity_xaxis', 'angular_velocity_yaxis', 'angular_velocity_zaxis', 'angle_xaxis', 'angle_yaxis', 'angle_zaxis', 'acceleration_xaxis_delta', 'acceleration_yaxis_delta', 'acceleration_zaxis_delta', 'acceleration_xaxis_delta_sum', 'acceleration_yaxis_delta_sum', 'acceleration_zaxis_delta_sum', 'acceleration_xaxis_corner', 'acceleration_yaxis_corner', 'acceleration_zaxis_corner', 'tags' ]


		data_points_attributes = params[:_json]
		data_points_attributes ||= [ params ]


		DataPoint.bulk_insert do |worker|
			data_points_attributes.each do |data_point_attributes|
				attrs = {}

				attrs[:raw_data] = data_point_attributes.to_json

				property_names.each do |property_name|
					attrs[property_name.to_sym] = data_point_attributes[property_name]
				end

				if attrs[:logged_at].present?
					attrs[:logged_at] = DateTime.parse( attrs[:logged_at] )
				elsif data_point_attributes[:timestamp].present?
					attrs[:logged_at] = Time.at( data_point_attributes[:timestamp].to_f )
				elsif data_point_attributes[:time_now].present?
					attrs[:logged_at] = Time.at( data_point_attributes[:time_now].to_f )
				end

				if data_point_attributes[:time_start].present?
					attrs[:time_start] = Time.at( data_point_attributes[:time_start].to_f )
				end

				worker.add(attrs)
			end
		end

	end

	def index
		@limit = params[:limit] || 500

		# last_data_point = DataPoint.last
		# @seconds_per_datapoint = 6
		# @seconds_per_datapoint = ( 60.0 / DataPoint.where( created_at: last_data_point.created_at - 1.minute..last_data_point.created_at ).count ).round if last_data_point.present?

		@data_points = DataPoint.all
		@data_points = @data_points.with_all_tags( params[:tags] ) if params[:tags].present?
		@data_points = @data_points.where( tags: '{}' ) if params[:no_tags].present?
		@data_points = @data_points.where( device_id: params[:device_id] ) if params[:device_id].present?
		@data_points = @data_points.where( 'logged_at > ?', params[:logged_since_seconds_ago].to_i.seconds.ago ) if params[:logged_since_seconds_ago].present?


		last_index = params[:since] unless params[:since].blank?
		last_index ||= ( @data_points.order(id: :desc).offset(@limit).limit(1).pluck(:id).first || 0 )

		@data_points = @data_points.where( 'id > ?', last_index )
		@data_points = @data_points.order( id: :asc ).limit(@limit)

		render layout: false, status: 200

	end

	def tag_new_with

		@data_points = DataPoint.all
		@data_points = @data_points.where( device_id: params[:device_id] ) if params[:device_id].present?
		@data_points.tag_new_with( params[:tags] )

		render plain: 'OK', layout: false, status: 200
	end

	def twod

		render layout: false

	end

	def live

		render layout: false

	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def color_from_integer( i )

		r = 0
		g = 0
		b = 0

		if i < 256
			r = i
		elsif i < 512
			r = 255
			g = (i - 255)
		elsif i < 768
			r = 255 - (i - 511)
			g = 255
		elsif i < 1024
			g = 255
			b = (i - 768)
		elsif i < 1280
			g = 255 - (i - 1023)
			b = 255
		elsif i < 1536
			b = 255
			r = (i - 1280)
		elsif i < 1792
			b = 255 - (i - 1535)
			r = 255
		else
		end


		[ r, g, b ]

	end

end

app/views/data/live.html.haml
%html
	%head
		:css
			body {
				padding: 0;
				margin: 0;
			}
			#myCanvas {
				width: 100vw;
				height: 100vh;
			}

		= javascript_include_tag 'http://paperjs.org/assets/js/paper.js'
		= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'

		:javascript
			$(function(){

				var dims = [ '#{(params[:dims]||'x,y').split(',').first}', '#{(params[:dims]||'x,y').split(',').last}' ]
				var other_dim = '#{([ 'x','y','z' ] - [ (params[:dims]||'x,y').split(',').first,(params[:dims]||'x,y').split(',').last ]).first}'
				var dim_left = dims[0]
				var dim_bottom = dims[1]
				var last_data_point = null;
				var current_data_point = null;

				var canvas = document.getElementById('myCanvas');
				paper.setup(canvas);
				var acceleration_path = new paper.Path();
				acceleration_path.strokeColor = 'black';

				var sum_acceleration_path = new paper.Path();
				sum_acceleration_path.strokeColor = 'red';

				var velocity_path = new paper.Path();
				velocity_path.strokeColor = 'blue';

				var acceleration_last_point = new paper.Point(paper.view.size.width / 3, paper.view.size.height / 2);
				var sum_acceleration_last_point = new paper.Point(paper.view.size.width / 3 * 2, paper.view.size.height / 2);
				var velocity_last_point = new paper.Point(paper.view.size.width / 2, paper.view.size.height / 2);

				acceleration_path.moveTo(acceleration_last_point);
				sum_acceleration_path.moveTo(sum_acceleration_last_point);
				velocity_path.moveTo(velocity_last_point);

				paper.view.draw();

				function draw_data_point( data_point ) {
					acceleration_last_point = acceleration_last_point.add([ data_point['acceleration_'+dim_left+'axis_delta'] * 100, data_point['acceleration_'+dim_bottom+'axis_delta'] * 100 ])
					acceleration_path.lineTo(acceleration_last_point);

					sum_acceleration_last_point = sum_acceleration_last_point.add([ data_point['acceleration_'+dim_left+'axis_delta_sum'], data_point['acceleration_'+dim_bottom+'axis_delta_sum'] ])
					sum_acceleration_path.lineTo(sum_acceleration_last_point);

					velocity_last_point = velocity_last_point.add([ data_point['acceleration_'+dim_left+'axis_delta_sum'] * data_point.time_delta, data_point['acceleration_'+dim_bottom+'axis_delta_sum'] * data_point.time_delta ])
					velocity_path.lineTo(velocity_last_point);
				}

				function fetch_data() {
					var since = ''
					if ( last_data_point ) since = last_data_point.id

					$.getJSON( "#{raw data_path( params.permit( :dims, :limit, :device_id ).merge( format: :json, tags: params[:tags], logged_since_seconds_ago: 30 ) )}&since="+since, function( data ) {

						$(data).each(function(index,data_point){

							data_point.last_data_point = ( last_data_point || data_point )
							data_point.last_data_point.next_data_point = data_point
							last_data_point = data_point

							if ( !current_data_point ) current_data_point = data_point

						})

						start_walking_list()

						setTimeout(function(){
							fetch_data();
						}, 1000 )
					});
				}

				var walk_list = null;

				function start_walking_list() {
					if ( !walk_list && current_data_point && current_data_point.next_data_point ) {
						console.log('start walking', current_data_point)
						walk_list = function() {
							if ( current_data_point.next_data_point ) {
								console.log('take step', current_data_point)
								var this_data_point = current_data_point
								draw_data_point( this_data_point )
								current_data_point = current_data_point.next_data_point
								setTimeout( walk_list, current_data_point.time_delta * 1000 )
								this_data_point.last_data_point = null; // dereference old nodes
							} else {
								console.log('stop walking', current_data_point, current_data_point.next_data_point)
								walk_list = null;
							}
						}
						walk_list()
					} else if ( walk_list ) {
						console.log('already walking')
					} else {
						console.log('not ready to walk yet')
					}
				}

				fetch_data();
			})
	%body
		%canvas#myCanvas{ resize: true }

app/views/data/twod.html.haml
%html
	%head
		:css
			body {
				padding: 0;
				margin: 0;
			}
			#myCanvas {
				width: 100vw;
				height: 100vh;
			}

		= javascript_include_tag 'http://paperjs.org/assets/js/paper.js'
		= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'

		:javascript
			$(function(){

				var dims = [ '#{(params[:dims]||'x,y').split(',').first}', '#{(params[:dims]||'x,y').split(',').last}' ]
				var other_dim = '#{([ 'x','y','z' ] - [ (params[:dims]||'x,y').split(',').first,(params[:dims]||'x,y').split(',').last ]).first}'
				var dim_left = dims[0]
				var dim_bottom = dims[1]
				var last_data_point = null;
				var current_data_point = null;

				var canvas = document.getElementById('myCanvas');
				paper.setup(canvas);
				var acceleration_path = new paper.Path();
				acceleration_path.strokeColor = 'black';

				var sum_acceleration_path = new paper.Path();
				sum_acceleration_path.strokeColor = 'red';

				var velocity_path = new paper.Path();
				velocity_path.strokeColor = 'green';

				var corner_acceleration_path = new paper.Path();
				corner_acceleration_path.strokeColor = 'blue';

				var major_corner_acceleration_path = new paper.Path();
				major_corner_acceleration_path.strokeColor = 'purple';


				var acceleration_last_point					= new paper.Point(paper.view.size.width / 6 * 1, paper.view.size.height / 2);
				var corner_acceleration_last_point			= new paper.Point(paper.view.size.width / 6 * 2, paper.view.size.height / 2);
				var major_corner_acceleration_last_point	= new paper.Point(paper.view.size.width / 6 * 3, paper.view.size.height / 2);
				var velocity_last_point						= new paper.Point(paper.view.size.width / 6 * 4, paper.view.size.height / 2);
				var sum_acceleration_last_point				= new paper.Point(paper.view.size.width / 6 * 5, paper.view.size.height / 2);


				var acceleration_start_point = acceleration_last_point
				var sum_acceleration_start_point = sum_acceleration_last_point
				var velocity_start_point = velocity_last_point
				var corner_acceleration_start_point = corner_acceleration_last_point
				var major_corner_acceleration_start_point = major_corner_acceleration_last_point

				acceleration_path.moveTo(acceleration_start_point);
				sum_acceleration_path.moveTo(sum_acceleration_start_point);
				velocity_path.moveTo(velocity_start_point);
				corner_acceleration_path.moveTo(corner_acceleration_start_point);
				major_corner_acceleration_path.moveTo(major_corner_acceleration_start_point);

				paper.view.draw();

				function draw_data_point( data_point ) {
					acceleration_last_point = acceleration_last_point.add([ data_point['acceleration_'+dim_left+'axis_delta'] * 100, data_point['acceleration_'+dim_bottom+'axis_delta'] * 100 ])
					acceleration_path.lineTo(acceleration_last_point);

					sum_acceleration_last_point = sum_acceleration_last_point.add([ data_point['acceleration_'+dim_left+'axis_delta_sum'], data_point['acceleration_'+dim_bottom+'axis_delta_sum'] ])
					sum_acceleration_path.lineTo(sum_acceleration_last_point);

					velocity_last_point = velocity_last_point.add([ data_point['acceleration_'+dim_left+'axis_delta_sum'] * data_point.time_delta, data_point['acceleration_'+dim_bottom+'axis_delta_sum'] * data_point.time_delta ])
					velocity_path.lineTo(velocity_last_point);

					if( data_point['acceleration_'+dim_left+'axis_corner'] || data_point['acceleration_'+dim_bottom+'axis_corner'] ) {
						corner_acceleration_last_point = new paper.Point( corner_acceleration_start_point.x + data_point['acceleration_'+dim_left+'axis_delta_sum'] * 100, corner_acceleration_start_point.y + data_point['acceleration_'+dim_bottom+'axis_delta_sum'] * 100 )
						corner_acceleration_path.lineTo(corner_acceleration_last_point);
					}

				}

				function fetch_data() {
					var since = '#{params[:since]}'
					if ( last_data_point ) since = last_data_point.id

					var url = "#{raw data_path( params.permit( :dims, :limit, :device_id, :logged_since_seconds_ago ).merge( format: :json, tags: params[:tags] ) )}&since="+since

					$.getJSON( url, function( data ) {

						$(data).each(function(index,data_point){

							data_point.last_data_point = ( last_data_point || data_point )
							data_point.last_data_point.next_data_point = data_point
							last_data_point = data_point

							if( data_point.last_data_point == data_point ) {
								data_point.corner_xaxis = true
								data_point.corner_yaxis = true
								data_point.corner_zaxis = true
							}

							if ( !current_data_point ) current_data_point = data_point

						})

						start_walking_list()

						if( data.length > 0 ) fetch_data();
					});
				}

				var walk_list = null;

				function start_walking_list() {
					if ( !walk_list && current_data_point && current_data_point.next_data_point ) {
						// console.log('start walking', current_data_point)
						walk_list = function() {
							if ( current_data_point.next_data_point ) {
								// console.log('take step', current_data_point)
								var this_data_point = current_data_point
								draw_data_point( this_data_point )
								current_data_point = current_data_point.next_data_point
								setTimeout( walk_list, current_data_point.time_delta * 1000 )
								this_data_point.last_data_point = null; // dereference old nodes
							} else {
								// console.log('stop walking', current_data_point, current_data_point.next_data_point)
								walk_list = null;
							}
						}
						walk_list()
					} else if ( walk_list ) {
						// console.log('already walking')
					} else {
						// console.log('not ready to walk yet')
					}
				}

				fetch_data();
			})
	%body
		%canvas#myCanvas{ resize: true }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HumeBridge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>